name = "edge-computing"
main = "src/index.ts"
compatibility_date = "2022-07-22"

# vou adicionar vari√°veis de ambiente
[vars]
UPSTASH_REDIS_REST_URL = "https://global-daring-grouper-30859.upstash.io"

# [secrets]
# UPSTASH_REDIS_REST_TOKEN
